### ISSUE TITLE
PCBWays file is corrupted

### ISSUE THREAD

**Issue by ethicstechOSS** [FabienFerrero/UCA_Board#1]
Hi Fabien Ferrero,
I would like to thank this project and UCA based antenna should be very useful when we target the portable LoRa based project to avoid the external antenna. 

I found that the "Ordering a PCBWays" file under document/tutorial folder is either corrupted or in wrong format. 

Keep it up your great job. 

TIA,
Prakash

**Comment by FabienFerrero** [comment]
Hi Prakash !

Thanks a lot for your comment, I've corrected the pdf file and updated it.

Regards

Fabien
