### ISSUE TITLE
Short circuit between Antenna and Ground plane

### ISSUE THREAD

**Issue by man4567890** [FabienFerrero/UCA_Board#10]
There seem to be a short circuit between the ground plane and the Antenna connection pad
![image](https://user-images.githubusercontent.com/53390181/62832091-8d312500-bc29-11e9-800c-821f715fd545.png)
Even on the boards I ordered from a PCB manufacturer, with nothing populated on the board, it shows as a full short
![image](https://user-images.githubusercontent.com/53390181/62832159-aededc00-bc2a-11e9-8380-3cbdd4f9608d.png)
![image](https://user-images.githubusercontent.com/53390181/62832167-be5e2500-bc2a-11e9-8ac5-5f2b8e38aa13.png)

If I cut the track in the A, the board works as expected
![image](https://user-images.githubusercontent.com/53390181/62832213-3debf400-bc2b-11e9-9237-020b22bf6ebd.png)

Is the short on purpose? Must it be cut?

**Comment by FabienFerrero** [comment]
Hi,
I know that it can seem strange, but this type of antenna (Inverted F antenna) is optimized thanks to this short circuit.
By cutting this line, you will reduce by 3-4dB the gain of the antenna.

So don't worry about the short circuit.

Kind regards
