### ISSUE TITLE
How to tune the antena for a 1mm board.

### ISSUE THREAD

**Issue by ludiazv** [FabienFerrero/UCA_Board#11]
Thanks Fabien for this project.

  Some manufactures do not offer 0.8mm on some services. The thiner they offer is 1mm. Can the antenna be tuned for that thickness or requires a new desing?

**Comment by FabienFerrero** [comment]
Dear Ludiazv,

The antenna can be easily tuned by cutting the top line (see document on antenna tuning).
For 1mm pcb thickness, the actual antenna frequency will be probably decreased by few MHz, so a very short cut (1 mm max) will be needed. Whatever, if you keep actual configuration, the decrease in performance will be very small

**Comment by ludiazv** [comment]
Thanks a lot.
